/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { ResponseStatus } from './responseStatus';


export interface GetCategoryBySlugResponse { 
    category: Category;
    status: ResponseStatus;
}

