/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Address { 
    /**
     *  street name, ie: 1723 NW 23rd Ave.
     */
    street: string;
    /**
     *  city name
     */
    city: string;
    /**
     *  state or province name
     */
    stateProvince: string;
    /**
     *  IISO 3166-1 alpha-2 country code. https:en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
     */
    country: string;
    /**
     *  postal or zip code
     */
    postalCode: string;
    /**
     *  indicates if this is a default address
     */
    isDefault: boolean;
}

