/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseStatus { 
    /**
     *  RFC http status code, ie. 204, etc - https:go.dev/src/net/http/status.go
     */
    statusCode: number;
    /**
     *  status message
     */
    statusMessage: string;
}

