/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';


export interface CustomerAccount { 
    /**
     *  customer id
     */
    id: number;
    billing_address: Address;
    /**
     *  collection of Address objects
     */
    shipping_addresses: Array<Address>;
}

