/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { PermissionGroup } from './permissionGroup';


export interface GetUserByIdResponse { 
    user?: User;
    /**
     *  User object
     */
    permission_groups?: Array<PermissionGroup>;
}

