/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Store { 
    /**
     *  store id
     */
    id: number;
    /**
     *  unique url
     */
    url?: string;
    /**
     *  store name
     */
    name?: string;
    /**
     *  description
     */
    description?: string;
    /**
     *  indicates if this is the default store
     */
    is_default?: boolean;
}

