/**
 * Admin Gateway API
 * admin gateway api
 *
 * The version of the OpenAPI document: 1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    /**
     *  user id
     */
    id?: number;
    /**
     *  first name
     */
    first_name?: string;
    /**
     *  last name
     */
    last_name?: string;
    /**
     *  email address
     */
    email?: string;
    /**
     *  password
     */
    password?: string;
}

